// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function GetContent():Promise<string>;

export function GetCurrentFile():Promise<string>;

export function NewFile():Promise<void>;

export function OpenFile():Promise<string>;

export function SaveAsFile():Promise<boolean>;

export function SaveFile():Promise<boolean>;

export function SetContent(arg1:string):Promise<void>;
