// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetContent() {
  return window['go']['main']['App']['GetContent']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveAsFile() {
  return window['go']['main']['App']['SaveAsFile']();
}

export function SaveFile() {
  return window['go']['main']['App']['SaveFile']();
}

export function SetContent(arg1) {
  return window['go']['main']['App']['SetContent'](arg1);
}
